import type { Metadata } from "next";
import localFont from "next/font/local";
import "./_styles/main.scss";
import styles from "./layout.module.scss";

const pretendard = localFont({
  src: "./_fonts/Pretendard.woff",
  variable: "--font-pretendard",
  weight: "normal",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable}`}>
        <header className={styles.header}>
          <div className={styles["header-inner"]}>
            <h1>smwaterjet</h1>
            <nav className={styles.nav}>
              <h2>메뉴</h2>
              <ul className={styles["nav-list"]}>
                <li>
                  <a href="/company/greeting">회사소개</a>
                </li>
                <li>
                  <a href="/business">사업영역</a>
                </li>
                <li>
                  <a href="/equipment">주요설비</a>
                </li>
                <li>
                  <a href="/performance/overview">사업실적</a>
                </li>
                <li>
                  <a href="/support/notice">고객지원</a>
                </li>
              </ul>
            </nav>
          </div>
        </header>
        <main className={styles.main}>
          <div className={styles["main-inner"]}>{children}</div>
        </main>
        <footer className={styles.footer}></footer>
      </body>
    </html>
  );
}
