import type { Metadata } from "next";
import localFont from "next/font/local";
import "./_styles/main.scss";
import styles from "./layout.module.scss";
import Header from "./_components/Header/Header";
import Footer from "./_components/Footer/Footer";
import Banner from "./_components/Banner/Banner";
// import localFont from 'next/font/local';

const pretendard = localFont({
  src: "./fonts/SpoqaHanSansNeo-Medium.otf",
  display: "swap",
  // weight: ["100", "900"], // 폰트 가중치 범위 설정
  // variable: "--font-pretendard",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${styles.body} ${pretendard}`}>
        <Header />
        <Banner />
        <main className={styles.main}>
          <div className={styles["main-inner"]}>{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
